image: alpine

pages:
  script:
  - apk update && apk add doxygen graphviz ttf-freefont
    #- doxygen docs/doxygen.conf
  - doxygen Doxyfile 
  - mv docs/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

